### ISSUE TITLE
Cache path and cache_path_tmp should be machine independent

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#24]
In line 15-16. the variables `cache_path*` are defined assuming that `/srv` exists https://github.com/terraref/traitvis-webapp/blob/master/cache-refresh.R#L15

This makes the app fail if the directory does not exist. This location should be a relative path.

This was implemented in https://github.com/terraref/traitvis-webapp/commit/aac431faa32632b1e0d479bbe79a84b903e73c42 so I am assigning to @max-zilla to at least help determine the rationale and a suitable alternative

**Comment by dlebauer** [comment]
@kimberlyh66 can help but assigned to @max-zilla because it isn't clear what the requirements are from the side of deploying on workbench / openstack

**Comment by max-zilla** [comment]
https://github.com/terraref/traitvis-webapp/pull/25 This I believe addresses the issue, it will try to make a cache folder in the same dir as the R script (just issues a warning if it exists already)

**Comment by Chris-Schnaufer** [comment]
Closing as fixed
