### ISSUE TITLE
Update webapp to use 'label field' with variable name

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#31]
Replace code that simply removes underscores and converts variable names to uppercase so that it uses the label field in the variables table.

I updated all of the labels in https://github.com/terraref/tutorials/issues/178 so this should work

Also, when the units field is not null or empty, add them in parentheses after the label (<units>)

**Comment by kimberlyh66** [comment]
There appears to be some labels that already have units or some kind of note in parentheses. Do you think we should remove the content in parentheses before trying to add (units) after label?

Examples:

`Carotenoid index (Chappelle)`

`Transformed Chlorophyll Absorption in Reflectance Index/Optimized Soil-Adjusted Vegetation Index (TCARI/OSAVI )`

`Coleoptile Color (1 = green, 2 = red)`

`Specific Leaf Area (m2 kg-1)`

**Comment by dlebauer** [comment]
Better to expect that these won't be there. I've updated the database, but it might take a day before you can sync the changes to a local instance - you can ignore these for now.

**Comment by kimberlyh66** [comment]
When you have time, could you also update the following variables that also have a label that contains content in parentheses?

1.) SR750_710, Simple Ratio 750/710 Zarco-Tejada & Miller (ZM)
2.) CarChap, Carotenoid index (Chappelle)
3.) Car1Black, Carotenoid index (Blackburn)
4.) Car2Black, Carotenoid index 2 (Blackburn)
5.) AntGamon, Anthocyanin (Gamon)
6.) PRI586, Photochemical reflectance index (586)
7.) PRI512, Photochemical reflectance index (512)
8.) AntGitelson, Anthocyanin (Gitelson)
9.) aboveground_fresh_biomass, Fresh Biomass (kg/ha)

**Comment by dlebauer** [comment]
done!

**Comment by kimberlyh66** [comment]
Thanks for updating

**Comment by kimberlyh66** [comment]
Variable name has been updated to be label field. 

See pull request #39.

**Comment by dlebauer** [comment]
looks great, pr has been merged
