### ISSUE TITLE
Check season 7 variable dropdown

### ISSUE THREAD

**Issue by kimberlyh66** [terraref/traitvis-webapp#33]
Check why `surface_temperature` is the only variable displayed in season 7 variable selection dropdown for all sub experiments.

**Comment by kimberlyh66** [comment]
@dlebauer 

Only 3/5 of season 7 sub experiments are displayed in the current deployed version of traitvis: `Border`, `Sorghum Mutants: F2 families`, `Pioneer Hybrid Uniformity Blocks`

All of Duke's season 7 data is associated with a sub experiment that is not yet displayed (`MAC Season 7: Stay-green RILs F10`). However, for all variables to appear for this experiment, the start_date needs to be changed to `2018-08-27` like all other season 7 experiments. Currently start_date is `2018-10-30` and all of Duke's trait data have a date of `2018-10-08`.

**Comment by Chris-Schnaufer** [comment]
@kimberlyh66 Is this one ready for review?

**Comment by kimberlyh66** [comment]
@Chris-Schnaufer Yes, this is ready for review
