### ISSUE TITLE
Add tables containing links to BETYdb variable and method records 

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#37]
1) add link to methods record in BETYdb

2) add link to variable record in BETYdb

**Comment by kimberlyh66** [comment]
@dlebauer 

Just wanted to clarify with you if it is the method name in the trait plot legend that you would like to have hyperlinked to a method page in BETYdb?

I have been looking up ways to hyperlink text in a ggplot, but the approaches that I have seen mostly use the gridSVG package. This requires converting a ggplot into a SVG image, which takes away the hover feature for the trait plot. Do you know of any other way to hyperlink text in a ggplot that doesn't require conversion to a SVG image?

**Comment by dlebauer** [comment]
definitely not worth doing this, but might be worth having a table at the bottom of the page that contains information from the variables and methods tables. That would remove the need to have a link, since the information would be provided on the page.

**Comment by kimberlyh66** [comment]
This issue has been changed from linking method name in trait plot legend to BETYdb method record to adding links to BETYdb variable and method records using a table

**Comment by Chris-Schnaufer** [comment]
Waiting to review Pull Request

**Comment by dlebauer** [comment]
closed by https://github.com/terraref/traitvis-webapp/pull/44
