### ISSUE TITLE
Add figure legends

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#38]
For example, with the violin plots, explain that it is with a timeseries, contains a violin plot with a boxplot and outliers 

Look to the geom_violin and geom_boxplot for definitions of where the quantiles are and what is considered an outlier. 

Explain that if a cultivar is selected it will show draw a line and dots to display the cultivar specific data

Most plots are violin+boxplot implementation https://github.com/terraref/traitvis-webapp/blob/master/app.R#L165

Where the data are categorical the legend should change: https://github.com/terraref/traitvis-webapp/blob/master/app.R#L158

**Comment by kimberlyh66** [comment]
A caption has been added for the trait plot. See pull request #51.

**Comment by Chris-Schnaufer** [comment]
Waiting on Pull Request
