### ISSUE TITLE
Add time series of heritability below trait time series plots

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#42]
For each season x date x trait, compute heritability and plot with date on the x axis and repeatability on the y axis: 

Sample code:

```r
library(heritability)
h2<-repeatability(data.vector=phen[,grep(“canopy_height”,names(phen))],geno.vector=phen$cultivar)
```

For more context: 
* https://articles.extension.org/pages/61006/estimating-heritability-and-blups-for-traits-using-tomato-phenotypic-data
* https://terra-ref.slack.com/archives/C2MF45G2D/p1565297929008600

**Comment by dlebauer** [comment]
repeatability and heritability are similar calculations; repeatability is within season heritability

so we will use the `heritability::repeatability()` function and have y axis 'repeatability (within season heritability)'

**Comment by dlebauer** [comment]
![image](https://user-images.githubusercontent.com/464871/63128433-cb03b580-bf69-11e9-85b1-1b0090b5b267.png)

**Comment by kimberlyh66** [comment]
Do you want repeatability to be calculated for a specific date and trait for all sub experiments in a season or just for a single sub experiment?

**Comment by dlebauer** [comment]
The same sub experiment / subset of the data used in the time series plot above.

**Comment by kimberlyh66** [comment]
Pull request #54
