### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#43]
The README needs some reorganization so that it is useful.

The deployment / kubernetes stuff can go to the end. 

In the beginning it should help a user get it up and running on their own computer. But the instructions are all mixed up.

The content about running postgres locally with the shell scripts can be removed ... if the docker stuff works that should be sufficient.

These are the steps that I used (but let me know if this is the recommended path!)

How to get the database running in docker:

```sh
wget https://raw.githubusercontent.com/terraref/brapi/master/docker-compose.yml
## or does the docker-compose file in this repo work? should it?
docker-compose up -d postgres
docker-compose run --rm bety initialize
docker-compose run --rm bety sync
```

How to refresh the cache (is this the right way?)

```r
Sys.setenv(bety_host = 'localhost')
source('cache-refresh.R')
```

Finally, the `shiny::runGitHub()` function is currently out of date.

**Comment by Chris-Schnaufer** [comment]
Waiting on Pull Request review
