### ISSUE TITLE
When cultivar is selected, make lines and points black

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#48]
Currently, the default plot is red, and when a cultivar is selected, it is not clear which points are assoicated with the cultivar. 

When a cultivar is selected, the points and lines connecting them should be black.

Also, the connecting lines should be separated by method so that they don't jump between methods.

![image](https://user-images.githubusercontent.com/464871/63725495-65d47d80-c80f-11e9-950f-212dcead7778.png)

Something like

![image](https://user-images.githubusercontent.com/464871/63725683-f57a2c00-c80f-11e9-9952-6cb08ccba155.png)

also with black points

![image](https://user-images.githubusercontent.com/464871/63725688-f9a64980-c80f-11e9-9fa8-958eb4583b88.png)

**Comment by MagicMilly** [comment]
Have changed the lines and points and corresponding descriptive text to black, but I'm having trouble reproducing the other issue of other methods and running into some weird plots. ![Screen Shot 2019-11-20 at 10.25.58.png](https://images.zenhubusercontent.com/5dae068e86447a00015c37c5/a35da11f-909f-4951-be6b-ca315100f01c)

**Comment by MagicMilly** [comment]
Closing this and creating new issue for connecting lines being separated by method.
