### ISSUE TITLE
Sort list of variables, list of cultivars, and season tabs

### ISSUE THREAD

**Issue by dlebauer** [terraref/traitvis-webapp#50]
will make it easier to find a specific cultivar

see here they are randomly sorted:

![image](https://user-images.githubusercontent.com/464871/65276861-8970a800-dadd-11e9-8572-28e2aeda5901.png)

**Comment by KristinaRiemer** [comment]
Might as well do this for the variable drop down list also.

**Comment by KristinaRiemer** [comment]
Also @dlebauer are the tabs for the seasons in a particular order? They're not in chronological order.

**Comment by dlebauer** [comment]
Yes - Would be nice to also have the tabs in order


-- 
David LeBauer
Director of Data Sciences
CALS Comm and Technologies
THE UNIVERSITY OF ARIZONA

BSRL, 207
1230 N Cherry Ave | Tucson, AZ 85721
Office: 520-621-4381 | Cell: 760-468-8621
dlebauer@arizona.edu

*datascience.cals.arizona.edu <https://datascience.cals.arizona.edu>*
orcid <https://orcid.org/0000-0001-7228-053X> | twitter
<https://twitter.com/dlebauer> | github <https://www.github.com/dlebauer> |
linkedin <https://www.linkedin.com/in/dlebauer/>

**Comment by KristinaRiemer** [comment]
This would be a good issue for @MagicMilly to start with, as it is fairly straightforward to implement.

**Comment by MagicMilly** [comment]
Yes, thank you @KristinaRiemer for suggesting this issue for me to start with and for offering your help! I will check in with you on my progress just for a sanity / time check.
